[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'Shougo/deoplete-rct'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'rhysd/vim-clang-format'

[[plugins]]
repo = 'justmao945/vim-clang'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'greyblake/vim-preview'

[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'beyondmarc/opengl.vim'

[[plugins]]
repo = 'tikhomirov/vim-glsl'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'elzr/vim-json'
